services:
  workspace:
    image: mcr.microsoft.com/vscode/devcontainers/java:21-jdk-bullseye
    init: true
    command: /bin/sh -c "while sleep 1000; do :; done"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ..:/home/vscode/workspace:cached
      - ~/.ssh:/home/vscode/.ssh
    working_dir: /home/vscode/workspace
    ports:
      - "8080:8080"
  backend-db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
    volumes:
      - backend-db-data:/var/lib/postgresql/data
      - ../data/db:/docker-entrypoint-initdb.d

volumes:
  backend-gradle-cache:
  backend-db-data: